apiVersion: v1
kind: Pod 
metadata: 
  name: qos-example
  namespace: qos-example
spec: 
  containers: 
  - name: qos-example
    image: nginx
    resources: 
      limits:   
        memory: "200Mi"
        cpu: "700m"
      requests: 
        memory: "200Mi"
        cpu: "700m"
  
