apiVersion: v1 
kind: PersistentVolumeList
metadata: 
  #name: nfs
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nfs01
  spec: 
    nfs: 
      path: /nfs/nfs-01
      server: 10.4.3.91
    capacity: 
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: mysc
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nfs02
  spec: 
    nfs: 
      path: /nfs/nfs-02
      server: 10.4.3.91
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: mysc
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nfs03
  spec: 
    nfs: 
      path: /nfs/nfs-03
      server: 10.4.3.91
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: mysc
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nfs04
  spec: 
    nfs: 
      path: /nfs/nfs-04
      server: 10.4.3.91
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: mysc

