apiVersion: v1
kind: Pod
metadata: 
  name: cpu-example
  namespace: cpu-example
spec: 
  containers: 
  - name: cpu-demo
    image: vish/stress
    resources: 
      limits: 
        cpu: 1 
      requests: 
        cpu: 0.5
    args: [" -cpus" , "2"]
