apiVersion: v1 
kind: Pod 
metadata: 
  name: pod1
spec: 
  volumes: 
  - name: v1
    persistentVolumeClaim: 
      claimName: pvc-hostpath-example
 
  containers: 
  - name: nginx1
    image: nginx 
    ports: 
    - containerPort: 80 
      name: http
    - containerPort: 443 
      name: https
    volumeMounts: 
    - name: v1
      mountPath: "/usr/share/nginx/html" 
