apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-hostpath-example
spec: 
  storageClassName: manual
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 3Gi
